# Generated by Django 6.0.5 on 2026-06-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_role_can_approve_role_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_mfa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
