# Generated by Django 6.0.5 on 2026-06-03 12:02

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=tickets.models.generate_ticket_id, editable=False, max_length=16, unique=True)),
                ('category', models.CharField(choices=[('it', 'IT Support'), ('core', 'Core Banking'), ('cards', 'Cards Team'), ('facilities', 'Facilities'), ('hr', 'Human Resources'), ('compliance', 'Compliance / Risk')], max_length=32)),
                ('problem_type', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('impact', models.CharField(choices=[('single', 'Single User'), ('team', 'Whole Team'), ('branch', 'Entire Branch')], max_length=16)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=16)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending Manager Approval', 'Pending Manager Approval'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=32)),
                ('account_or_card', models.CharField(blank=True, max_length=32, null=True)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=64, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
        ),
    ]
