# Generated by Django 6.0.5 on 2026-06-15 14:58

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=tickets.models.generate_ticket_id, editable=False, max_length=16, unique=True)),
                ('category', models.CharField(choices=[('it', 'IT Support'), ('core', 'Core Banking'), ('cards', 'Cards Team'), ('facilities', 'Facilities'), ('hr', 'Human Resources'), ('compliance', 'Compliance / Risk')], max_length=32)),
                ('problem_type', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('impact', models.CharField(choices=[('single', 'Single User'), ('team', 'Whole Team'), ('branch', 'Entire Branch')], max_length=16)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=16)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending Manager Approval', 'Pending Manager Approval'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending Manager Approval', max_length=32)),
                ('account_or_card', models.CharField(blank=True, max_length=32, null=True)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=64, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cash Reversal', 'Cash Reversal'), ('Software Install', 'Software Install'), ('Limit Increase', 'Limit Increase'), ('Access Request', 'Access Request')], max_length=32)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=16)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('step_number', models.IntegerField(default=1)),
                ('approver_role', models.CharField(default='HOD', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('problems', models.JSONField(default=list)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_sequence', models.JSONField(blank=True, default=list)),
                ('icon_name', models.CharField(choices=[('Monitor', 'Monitor / Workstations'), ('Banknote', 'Banknote / Core Banking'), ('CreditCard', 'CreditCard / ATM & Cards'), ('Wrench', 'Wrench / Facilities'), ('Users', 'Users / HR Services'), ('ShieldAlert', 'ShieldAlert / Compliance & Risk'), ('ShoppingBag', 'ShoppingBag / Procurement'), ('Scale', 'Scale / Legal'), ('Key', 'Key / Access Security'), ('Database', 'Database / Core Engine'), ('HelpCircle', 'HelpCircle / General Inquiries'), ('Activity', 'Activity / System Status'), ('UserCog', 'UserCog / Administrative Overrides'), ('Laptop', 'Laptop / Asset Provisioning')], default='Monitor', max_length=32)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='tickets.department')),
            ],
            options={
                'verbose_name_plural': 'Ticket Categories',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('public', 'Public Reply'), ('system', 'System Audit Log')], default='public', max_length=16)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
