# Generated by Django 6.0.5 on 2026-06-22 00:45

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=tickets.models.generate_ticket_id, editable=False, max_length=16, unique=True)),
                ('problem_type', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('impact', models.CharField(choices=[('single', 'Single User'), ('team', 'Whole Team'), ('branch', 'Entire Branch')], max_length=16)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=16)),
                ('status', models.CharField(default='New', max_length=64)),
                ('account_or_card', models.CharField(blank=True, max_length=32, null=True)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=64, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_name_cache', models.CharField(blank=True, max_length=128, null=True)),
                ('email_cache', models.CharField(blank=True, max_length=128, null=True)),
                ('action', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('Approval', 'Approval'), ('SLA', 'SLA'), ('Role', 'Role'), ('Auth', 'Auth'), ('Ticket', 'Ticket'), ('Config', 'Config'), ('Access', 'Access')], max_length=32)),
                ('ip_address', models.CharField(default='—', max_length=45)),
                ('device_meta', models.CharField(default='Internal', max_length=128)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Notice', 'Notice'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Info', max_length=16)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sla', 'SLA Warning'), ('assignment', 'Ticket Assignment'), ('mention', 'Comment Mention'), ('approval', 'Approval Request'), ('comment', 'New Comment'), ('status', 'Ticket Status Update'), ('system', 'System/Maintenance Alert')], max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=1000)),
                ('unread', models.BooleanField(default=True)),
                ('urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=16)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('step_number', models.IntegerField(default=1)),
                ('approver_role', models.CharField(default='HOD', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('approver_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.department')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('problems', models.JSONField(default=list)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_name', models.CharField(choices=[('Monitor', 'Monitor / Workstations'), ('Banknote', 'Banknote / Core Banking'), ('CreditCard', 'CreditCard / ATM & Cards'), ('Wrench', 'Wrench / Facilities'), ('Users', 'Users / HR Services'), ('ShieldAlert', 'ShieldAlert / Compliance & Risk'), ('ShoppingBag', 'ShoppingBag / Procurement'), ('Scale', 'Scale / Legal'), ('Key', 'Key / Access Security'), ('Database', 'Database / Core Engine'), ('HelpCircle', 'HelpCircle / General Inquiries'), ('Activity', 'Activity / System Status'), ('UserCog', 'UserCog / Administrative Overrides'), ('Laptop', 'Laptop / Asset Provisioning')], default='Monitor', max_length=32)),
                ('sla_critical_hours', models.PositiveIntegerField(default=1)),
                ('sla_high_hours', models.PositiveIntegerField(default=2)),
                ('sla_medium_hours', models.PositiveIntegerField(default=4)),
                ('sla_low_hours', models.PositiveIntegerField(default=8)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='tickets.department')),
            ],
            options={
                'verbose_name_plural': 'Ticket Categories',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategory', to_field='key'),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('public', 'Public Reply'), ('system', 'System Audit Log')], default='public', max_length=16)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.role')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tickets.ticketcategory')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('category', 'step_number')},
            },
        ),
    ]
