# Generated by Django 6.0.5 on 2026-06-16 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_role_can_approve_role_is_agent'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategory',
            name='approval_sequence',
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tickets.ticketcategory')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.role')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('category', 'step_number')},
            },
        ),
    ]
