# Generated by Django 6.0.5 on 2026-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticketcategory_approval_sequence_approvalstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='New', max_length=64),
        ),
    ]
