# Generated by Django 6.0.5 on 2026-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_approvalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Pending Manager Approval', 'Pending Manager Approval'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending Manager Approval', max_length=32),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment_type',
            field=models.CharField(choices=[('public', 'Public Reply'), ('system', 'System Audit Log')], default='public', max_length=16),
        ),
    ]
