# Generated by Django 6.0.5 on 2026-06-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_approvalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
