# Generated by Django 6.0.5 on 2026-06-18 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_resolved_at_alter_approvalrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='approver_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.department'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.department'),
        ),
    ]
