# Generated by Django 6.0.5 on 2026-06-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_approvalrequest_approver_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='sla_critical_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sla_high_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sla_low_hours',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sla_medium_hours',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
