# Generated by Django 6.0.5 on 2026-06-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketcategory_sla_critical_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
