# Generated by Django 6.0.5 on 2026-06-21 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_name_cache', models.CharField(blank=True, max_length=128, null=True)),
                ('email_cache', models.CharField(blank=True, max_length=128, null=True)),
                ('action', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('Approval', 'Approval'), ('SLA', 'SLA'), ('Role', 'Role'), ('Auth', 'Auth'), ('Ticket', 'Ticket'), ('Config', 'Config'), ('Access', 'Access')], max_length=32)),
                ('ip_address', models.CharField(default='—', max_length=45)),
                ('device_meta', models.CharField(default='Internal', max_length=128)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Notice', 'Notice'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Info', max_length=16)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
